services:

  ###########################################################
  #                    ZOOKEEPER SERVICE                    #
  ###########################################################
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1   # Official Confluent Zookeeper image
    container_name: zookeeper                 # Name shown in `docker ps`

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181            # Port used by Kafka to connect to Zookeeper
      ZOOKEEPER_TICK_TIME: 2000              # Heartbeat interval (standard value)

    ports:
      - "2181:2181"                          # Expose ZK so tools on your laptop can reach it


  ###########################################################
  #                     KAFKA BROKER                        #
  ###########################################################
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


    volumes:
      - kafka_data:/var/lib/kafka/data           # Persist Kafka data across restarts


###########################################################
#                DOCKER VOLUME DECLARATIONS               #
###########################################################
volumes:
  kafka_data:   # Named volume used by Kafka for durable storage
